version: '3'
services:

  flask:
      image: "flask-api:latest"
      build:
        context: ./api_flask_rag
        dockerfile: Dockerfile
      env_file:
      - .env
      ports:
        - "5000:5000"
      networks:
        - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network
    mem_limit: 8g              # Limite la mémoire à 8 Go
    mem_reservation: 4g


networks:
  app-network:
    driver: bridge


